### ISSUE TITLE
Missing bib info

### ISSUE THREAD

**Issue by dk58** [Brown-University-Library/iip_smr_web_project#1]
- Bibliography is missing (displays nothing) for some inscriptions even though the data is present in xml file (i.e. masa0772). 

- A cause: Bibliography for inscriptions with wrong format in xml tag “bibl” : [“bibl=IIP-xxx|nType=|n=834”] do not show up. Instead, it seems that it needs proper format “bibl” : [“bibl=IIP-xxx.xml|nType=|n=834”]. 

- Examples
    - [masa0772 example](http://dcdscit.services.brown.edu/iip_smr_dev/viewinscr/masa0772/) of Inscription with error 
    - [abil0001 example](http://dcdscit.services.brown.edu/iip_smr_dev/viewinscr/abil0001/) of Inscription with no error

- Note: error does not appear in production because the new code extracts some bib info in a different way, [using regex](https://github.com/Brown-University-Library/iip_smr_web_project/blob/87cd7c88286f95ee998f3bbcce77719602b817f7/iip_smr_web_app/views.py#L167) which does not account for the data inconsistency.

**Comment by emylonas** [comment]
for more info on this issue, see [(https://github.com/Brown-University-Library/iip-texts/issues/44)]

**Comment by emylonas** [comment]
fixing with commits d38c69e 0e55662
