### ISSUE TITLE
results page error

### ISSUE THREAD

**Issue by birkin** [Brown-University-Library/iip_smr_web_project#2]
- [example failing url](http://dcdscit.services.brown.edu/iip_smr_dev/results/?q=(notBefore:[-600%20TO%2010000])%20AND%20(notAfter:[-10000%20TO%20650]))

**Comment by birkin** [comment]
commenting out [this line](https://github.com/Brown-University-Library/iip_smr_web_project/blob/0f6c8dc178ffc3d8765e45bc6ed8497cf16d91d5/iip_smr_web_app/views.py#L79) should take care of this issue.

**Comment by dk58** [comment]
It worked! No error! Thank you
