### ISSUE TITLE
stories page error

### ISSUE THREAD

**Issue by birkin** [Brown-University-Library/iip_smr_web_project#3]
- [example url](http://dcdscit.services.brown.edu/iip_smr_dev/stories/theodotos)

**Comment by birkin** [comment]
- the issue has to do with the apostrophe in the string "king's command".
- whether the problem is in the [source-data](https://github.com/Brown-University-Library/iip_smr_web_project/blob/1a29659e13ec79f205630d43840a5dec2df174dd/iip_smr_web_app/static/stories/csv/stories.csv#L2) (line #2), or the [code](https://github.com/Brown-University-Library/iip_smr_web_project/blob/1a29659e13ec79f205630d43840a5dec2df174dd/iip_smr_web_app/views.py#L470), i'm not yet sure.

**Comment by dk58** [comment]
Fixed! Added 'encoding="utf-8"', encoding argument of csv open().

https://github.com/Brown-University-Library/iip_smr_web_project/blob/7c36aabf486e637441e976fe778398eea4e1e7f7/iip_smr_web_app/views.py#L489
